# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5a298871bfba1b7775819fa2a664b39fdd0df9c08459025af86cb4c2fc2f21faf1d06ddce52f68ae722bfcb24cc495ef6c77fb9a92d17141c239e177f4042f4

test:
  secret_key_base: 1d4362fad200c82d7be3ec3f3c8506d7c4b3f6eaa78fda851ee94a0a8e396bbbdb0e3e8a9cae729b8b3aa4d4db7601d82efa9b6e0b6882f99b0586cc1352f3fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
